// Build the public browser demos of the server products into ../demos/ (served by GitHub Pages):
//   npm run build:demo
// Each demo runs the real app code in the visitor's browser on an in-memory SQLite (sql.js).
import { build } from "esbuild";
import { readFileSync, writeFileSync, mkdirSync, readdirSync, copyFileSync, rmSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { ROOT } from "./lib.js";

const OUT = join(ROOT, "..", "demos");
const SHIMS = join(ROOT, "demo", "shims");
const APPS = [
  { name: "callcenter", exportName: "callcenterApp", title: "AZENK Call Center" },
  { name: "graduation", exportName: "graduationApp", title: "AZENK Graduation" },
  { name: "requests", exportName: "requestsApp", title: "AZENK Requests" },
];
const VERSION = new Date().toISOString().slice(0, 10).replace(/-/g, "");

// 1. Bake migration SQL into a virtual file system module.
const vfs = {};
const addDir = (dir) => { for (const f of readdirSync(dir)) if (f.endsWith(".sql")) vfs["/platform/" + relative(ROOT, join(dir, f))] = readFileSync(join(dir, f), "utf8"); };
addDir(join(ROOT, "core", "migrations"));
for (const a of APPS) addDir(join(ROOT, "apps", a.name, "migrations"));
writeFileSync(join(ROOT, "demo", "vfs.generated.js"), `// Generated by scripts/build-demo.js — do not edit.\nexport default ${JSON.stringify(vfs, null, 1)};\n`);

// 2. esbuild plugin: node:* → shims, import.meta.url → a stable virtual path per file.
const shimMap = { "fs/promises": "fs-promises.js", fs: "fs.js", path: "path.js", url: "url.js", crypto: "crypto.js", http: "http.js", sqlite: "sqlite.js" };
const platformPlugin = {
  name: "azenk-demo",
  setup(b) {
    b.onResolve({ filter: /^node:/ }, (args) => {
      const mod = args.path.slice(5);
      if (!shimMap[mod]) throw new Error(`No browser shim for ${args.path} (imported by ${args.importer})`);
      return { path: join(SHIMS, shimMap[mod]) };
    });
    // sql.js only touches fs/path/crypto in its Node branch, never in the browser.
    b.onResolve({ filter: /^(fs|path|crypto)$/ }, (args) => (/[\\/]sql\.js[\\/]/.test(args.importer) ? { path: args.path, namespace: "empty" } : undefined));
    b.onLoad({ filter: /.*/, namespace: "empty" }, () => ({ contents: "module.exports = {};", loader: "js" }));
    b.onLoad({ filter: /[\\/]platform[\\/](core|apps)[\\/].*\.js$/ }, (args) => {
      const src = readFileSync(args.path, "utf8");
      const virt = "file:///platform/" + relative(ROOT, args.path).replace(/\\/g, "/");
      return { contents: src.replaceAll("import.meta.url", JSON.stringify(virt)), loader: "js", resolveDir: dirname(args.path) };
    });
  },
};

rmSync(OUT, { recursive: true, force: true });
mkdirSync(join(OUT, "shared"), { recursive: true });
copyFileSync(join(ROOT, "node_modules", "sql.js", "dist", "sql-wasm.wasm"), join(OUT, "shared", "sql-wasm.wasm"));
copyFileSync(join(ROOT, "core", "public", "ui.js"), join(OUT, "shared", "ui.js"));
copyFileSync(join(ROOT, "core", "public", "ui.css"), join(OUT, "shared", "ui.css"));
copyFileSync(join(ROOT, "apps", "callcenter", "public", "favicon.svg"), join(OUT, "shared", "favicon.svg"));
const lic = (pkg) => { try { return readFileSync(join(ROOT, "node_modules", pkg, "LICENSE"), "utf8"); } catch { return "(see package)"; } };
writeFileSync(join(OUT, "shared", "THIRD-PARTY-LICENSES.txt"), ["AZENK browser demos include:", "",
  "sql.js (SQLite compiled to WebAssembly) — MIT; SQLite itself is public domain.", lic("sql.js"), "",
  "@noble/hashes — MIT", lic("@noble/hashes"), "", "buffer — MIT", lic("buffer")].join("\n"));

for (const a of APPS) {
  const dir = join(OUT, a.name);
  mkdirSync(dir, { recursive: true });
  await build({
    stdin: {
      contents: `import "./shims/globals.js";
import { startDemo } from "./runtime.js";
import { ${a.exportName} } from "../apps/${a.name}/app.js";
import { seedDemo } from "../apps/${a.name}/seed.js";
startDemo(${a.exportName}, seedDemo, { wasmUrl: "../shared/sql-wasm.wasm" });`,
      resolveDir: join(ROOT, "demo"),
      sourcefile: `demo-${a.name}.js`,
    },
    bundle: true,
    format: "iife",
    platform: "browser",
    target: ["es2022"],
    minify: true,
    legalComments: "eof",
    outfile: join(dir, "demo-runtime.js"),
    plugins: [platformPlugin],
    logLevel: "warning",
  });
  copyFileSync(join(ROOT, "apps", a.name, "public", "app.js"), join(dir, "app.js"));
  writeFileSync(join(dir, "index.html"), `<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <title>${a.title} — Demo</title>
  <meta name="description" content="Demo تفاعلي لنظام ${a.title} يعمل في متصفحك ببيانات تجريبية.">
  <meta name="robots" content="noindex, follow">
  <meta name="theme-color" content="#070a11">
  <link rel="icon" href="../shared/favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="../shared/ui.css?v=${VERSION}">
  <script src="demo-runtime.js?v=${VERSION}" defer></script>
  <script src="../shared/ui.js?v=${VERSION}" defer></script>
  <script src="app.js?v=${VERSION}" defer></script>
</head>
<body>
  <div id="root"><p class="loading">جارٍ تجهيز الـ Demo…</p></div>
  <noscript><p class="pad">يتطلب هذا الـ Demo تفعيل JavaScript.</p></noscript>
</body>
</html>
`);
  console.log(`built demos/${a.name}`);
}
